apiVersion: v1
kind: Pod
metadata:
  name: etcd-rover
  namespace: kube-system
spec:
  initContainers:
      ## auto compile drbd module and load in kernel. if install by user, should remove it
    - name: load-drbd
      image: alaudapublic/drbd-load:v1.0.0
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      env:
        - name: LB_HOW
          value: compile
      volumeMounts:
        - mountPath: /lib/modules/
          name: modules-dir
        - mountPath: /usr/src
          name: src-dir
    - name: config
      image: alaudapublic/etcd-rover-config:v1.0.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /etcd-rover/config/
          name: config
      args:
        - start
        ## gateway address
        - --gateway=192.168.2.1
        ## keepalived vip
        - --vip=192.168.3.3
        ## the network
        - --net=eth0
        ## node 1 ip
        - --nip1=192.168.3.1
        ## node 2 ip
        - --nip2=192.168.3.2
        ## node 1 storage device
        - --d1=/dev/loop0
        ## node 2 storage device
        - --d2=/dev/loop0
        ## node 1 host name
        - --n1=ovn-n3
        ## node 2 host name
        - --n2=ovn-n4
  containers:
    - name: etcd-rover
      image: alaudapublic/etcd-rover:v1.0.0
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
        runAsUser: 0
      volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /etcd-rover/config
          name: config
        - mountPath: /dev
          name: devices
        - mountPath: /lib/modules/
          name: modules-dir
  hostNetwork: true
  volumes:
    - name: src-dir
      hostPath:
        path: /usr/src
        type: Directory
    - name: modules-dir
      hostPath:
        path: /lib/modules/
        type: Directory
    - name: data
      hostPath:
        path: /etc/etcd-rover/
        type: DirectoryOrCreate
    - name: devices
      hostPath:
        path: /dev
        type: Directory
    - name: config
      emptyDir: {}
